package com.beyondxscratch.mandaloreexpress.domain.selection

import com.beyondxscratch.mandaloreexpress.domain.EqualityShould
import com.beyondxscratch.mandaloreexpress.domain.search.selection.SelectedSpaceTrain

class SelectedSpaceTrainShould : EqualityShould<SelectedSpaceTrain>